name: Delete old workflows
on:
  workflow_dispatch:
  schedule:
    - cron: '0 22 * * *'

jobs:
  del_runs:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 5
          keep_minimum_runs: 1
